version: '3'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  web:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file:
      - .env
    ports:
      - '5000:5000'
    volumes:
      - .:/app
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    depends_on:
      - redis
    command: celery -A "celery_worker:celery" worker --loglevel=INFO
